import { defineType, defineField } from "sanity";

export const program = defineType({
  name: "program",
  title: "Program",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category ID",
      type: "string",
      options: {
        list: [
          { title: "Autism Support", value: "autism" },
          { title: "Montessori", value: "montessori" },
          { title: "Early Learning", value: "early-learning" },
          { title: "Therapy", value: "therapy" },
          { title: "Life Skills", value: "life-skills" },
          { title: "Parent Support", value: "parent-support" },
          { title: "Arts & Crafts", value: "arts" },
          { title: "Cooking", value: "cooking" },
          { title: "Science", value: "science" },
          { title: "Sports", value: "sports" },
          { title: "Drama", value: "drama" },
          { title: "Music", value: "music" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "categoryLabel",
      title: "Category Label",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "categoryEmoji",
      title: "Category Emoji",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "section",
      title: "Client Section",
      type: "string",
      description: "Top-level website section this offering belongs to.",
      options: {
        list: [
          { title: "Haven Autism", value: "haven-autism" },
          { title: "Haven Montessori", value: "haven-montessori" },
          { title: "Party Hall", value: "party-hall" },
          { title: "Crash Courses for Adults", value: "crash-courses-adults" },
          { title: "Crash Courses for Children", value: "crash-courses-children" },
        ],
      },
    }),
    defineField({
      name: "subsectionLabel",
      title: "Subsection Label",
      type: "string",
      description: 'Examples: "Day Care Monthly", "Hall + Catering", "Quran Course".',
    }),
    defineField({
      name: "participantKind",
      title: "Participant Kind",
      type: "string",
      options: {
        list: [
          { title: "Child", value: "child" },
          { title: "Adult", value: "adult" },
          { title: "Event", value: "event" },
          { title: "Family", value: "family" },
        ],
        layout: "radio",
      },
      initialValue: "child",
    }),
    defineField({
      name: "ageGroup",
      title: "Age Group",
      type: "string",
      options: {
        list: [
          { title: "Ages 6–9", value: "ages-6-9" },
          { title: "Ages 10–13", value: "ages-10-13" },
          { title: "Ages 14+", value: "ages-14-plus" },
        ],
        layout: "radio",
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "ageLabel",
      title: "Age Label",
      type: "string",
      description: 'e.g. "Ages 8–12"',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "duration",
      title: "Duration",
      type: "string",
      description: 'e.g. "6 weeks · 90 min/session"',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "price",
      title: "Price",
      type: "string",
      description: 'e.g. "$180"',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "spotsLeft",
      title: "Spots Left",
      type: "number",
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: "totalSpots",
      title: "Total Spots",
      type: "number",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "dates",
      title: "Dates",
      type: "string",
      description: 'e.g. "Sat, Apr 26 — May 31"',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "time",
      title: "Time",
      type: "string",
      description: 'e.g. "10:00 AM"',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "image",
      title: "Main Image URL",
      type: "url",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "gallery",
      title: "Gallery Image URLs",
      type: "array",
      of: [{ type: "url" }],
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 2,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "longDescription",
      title: "Long Description",
      type: "text",
      rows: 5,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "whatKidsWillDo",
      title: "What Kids Will Do",
      type: "array",
      of: [{ type: "string" }],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "highlights",
      title: "Generic Highlights",
      type: "array",
      description: "Use for adult courses, events, daycare, and other offerings where child-specific wording does not fit.",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "instructor",
      title: "Instructor",
      type: "object",
      fields: [
        defineField({ name: "name", title: "Name", type: "string", validation: (r) => r.required() }),
        defineField({ name: "role", title: "Role", type: "string", validation: (r) => r.required() }),
        defineField({ name: "bio", title: "Bio", type: "text", rows: 2, validation: (r) => r.required() }),
        defineField({ name: "photo", title: "Photo URL", type: "url", validation: (r) => r.required() }),
      ],
    }),
    defineField({
      name: "type",
      title: "Program Type",
      type: "string",
      options: {
        list: [
          { title: "Haven Autism Program", value: "program" },
          { title: "Haven Montessori", value: "montessori" },
        ],
        layout: "radio",
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "campType",
      title: "Montessori Label",
      type: "string",
      description: "Optional label for Montessori cards. Older labels can remain until content is migrated.",
      options: {
        list: [
          { title: "Haven Montessori", value: "Haven Montessori" },
          { title: "Early Years", value: "Early Years" },
          { title: "Practical Life", value: "Practical Life" },
        ],
      },
      hidden: ({ parent }) => parent?.type !== "montessori",
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      initialValue: false,
      description: "Show this program on the homepage featured section",
    }),
    defineField({
      name: "order",
      title: "Sort Order",
      type: "number",
      description: "Lower numbers appear first",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "ageLabel",
      media: "image",
    },
  },
});
