/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as SummerCampRouteImport } from './routes/summer-camp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsAgeGroupRouteImport } from './routes/workshops.$ageGroup'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const SummerCampRoute = SummerCampRouteImport.update({
  id: '/summer-camp',
  path: '/summer-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsAgeGroupRoute = WorkshopsAgeGroupRouteImport.update({
  id: '/$ageGroup',
  path: '/$ageGroup',
  getParentRoute: () => WorkshopsRoute,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RegisterRoute,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRouteWithChildren
  '/summer-camp': typeof SummerCampRoute
  '/workshops': typeof WorkshopsRouteWithChildren
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/register/success': typeof RegisterSuccessRoute
  '/workshops/$ageGroup': typeof WorkshopsAgeGroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRouteWithChildren
  '/summer-camp': typeof SummerCampRoute
  '/workshops': typeof WorkshopsRouteWithChildren
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/register/success': typeof RegisterSuccessRoute
  '/workshops/$ageGroup': typeof WorkshopsAgeGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRouteWithChildren
  '/summer-camp': typeof SummerCampRoute
  '/workshops': typeof WorkshopsRouteWithChildren
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/register/success': typeof RegisterSuccessRoute
  '/workshops/$ageGroup': typeof WorkshopsAgeGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/register'
    | '/summer-camp'
    | '/workshops'
    | '/programs/$programId'
    | '/register/success'
    | '/workshops/$ageGroup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/register'
    | '/summer-camp'
    | '/workshops'
    | '/programs/$programId'
    | '/register/success'
    | '/workshops/$ageGroup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/register'
    | '/summer-camp'
    | '/workshops'
    | '/programs/$programId'
    | '/register/success'
    | '/workshops/$ageGroup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  SummerCampRoute: typeof SummerCampRoute
  WorkshopsRoute: typeof WorkshopsRouteWithChildren
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summer-camp': {
      id: '/summer-camp'
      path: '/summer-camp'
      fullPath: '/summer-camp'
      preLoaderRoute: typeof SummerCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/$ageGroup': {
      id: '/workshops/$ageGroup'
      path: '/$ageGroup'
      fullPath: '/workshops/$ageGroup'
      preLoaderRoute: typeof WorkshopsAgeGroupRouteImport
      parentRoute: typeof WorkshopsRoute
    }
    '/register/success': {
      id: '/register/success'
      path: '/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegisterRouteChildren {
  RegisterSuccessRoute: typeof RegisterSuccessRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSuccessRoute: RegisterSuccessRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface WorkshopsRouteChildren {
  WorkshopsAgeGroupRoute: typeof WorkshopsAgeGroupRoute
}

const WorkshopsRouteChildren: WorkshopsRouteChildren = {
  WorkshopsAgeGroupRoute: WorkshopsAgeGroupRoute,
}

const WorkshopsRouteWithChildren = WorkshopsRoute._addFileChildren(
  WorkshopsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RegisterRoute: RegisterRouteWithChildren,
  SummerCampRoute: SummerCampRoute,
  WorkshopsRoute: WorkshopsRouteWithChildren,
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
